// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb6l7J8nxN4Wtdit33ga3UNdRPA6IKfc0',
    appId: '1:216035418472:web:3ce656006d930bbdd7f6dd',
    messagingSenderId: '216035418472',
    projectId: 'auto-car-care-30970',
    authDomain: 'auto-car-care-30970.firebaseapp.com',
    storageBucket: 'auto-car-care-30970.appspot.com',
    measurementId: 'G-LH5PGHX0Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARsG5fkEZVGCuSX_IkwqcNZ-qKqa5-nVA',
    appId: '1:216035418472:android:1391783a1ab756edd7f6dd',
    messagingSenderId: '216035418472',
    projectId: 'auto-car-care-30970',
    storageBucket: 'auto-car-care-30970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt0CU6hfIpkagsP5jDWqpoB4N7uaSzZcc',
    appId: '1:216035418472:ios:501543fae7fd24bfd7f6dd',
    messagingSenderId: '216035418472',
    projectId: 'auto-car-care-30970',
    storageBucket: 'auto-car-care-30970.appspot.com',
    iosBundleId: 'com.example.autoCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt0CU6hfIpkagsP5jDWqpoB4N7uaSzZcc',
    appId: '1:216035418472:ios:572e2de52a42812fd7f6dd',
    messagingSenderId: '216035418472',
    projectId: 'auto-car-care-30970',
    storageBucket: 'auto-car-care-30970.appspot.com',
    iosBundleId: 'com.example.autoCare.RunnerTests',
  );
}
